//
//	Generated by MenuMaster V1.0 - Author:Liu Ying-Ting, E-Mail:laudean@so-net.net.tw
//
    Menus = new Array();
    Menus[0] = "m00,後台首頁,index.aspx#self,商品特區,#m01,進廣告,#m02,商品記事,#m03,文具大街,#m04,下載專區,#m05,客服信件處理,MessageList.aspx#self,會員管理,MemberList.aspx#self";
    
    
  
    Menus[1] = "m01,新增商品,ProductModify.aspx#self,管理商品,ProductList.aspx#self";
    Menus[2] = "m02,新增廣告,CFModify.aspx#self,管理廣告,CFList.aspx#self";
    Menus[3] = "m03,新增商品記事,NewsModify.aspx#self,管理商品記事,NewsList.aspx#self";
 Menus[4] = "m04,新增店家,StoreModify.aspx#self,管理文具大街,StoreList.aspx#self";
    Menus[5] = "m05,新增下載,WallpaperModify.aspx#self,管理下載專區,WallpaperList.aspx#self";
        